os:
  - linux
  - osx
language: rust
rust: 
#    - 1.0.0-beta
    - nightly
sudo: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev 

env:
  global:
    secure: "Kh4TbgJ7jQdL+dPOuNmPIWZfQJL6zDzc0clGIVQP3oP5yDt0qcxUziSxTzRmwoGDRdWDTr+TjdzUaRprfkGpwHsNBKcL90G8GcoBEyevtrzCCtBDUJJrtABaDAJCqa7Rl29d9UNXu01Cnpfskhxv6miwHOuQfzfFKe2OW+RwTy0="
install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.0/libsodium-1.0.0.tar.gz
- tar xvfz libsodium-1.0.0.tar.gz
- cd libsodium-1.0.0 && ./configure --prefix=/usr && make && sudo make install && cd ..
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
- tar xzf master.tar.gz
- mkdir kcov-master/build
- cd kcov-master/build
- cmake ..
- make
- sudo make install
- cd ../..
script:
- cargo build --verbose
- RUST_TEST_THREADS=1 cargo test
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages;
  cargo clean;
  cargo test --no-run;
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/maidsafe_vault-*;
