[package]
name = "maidsafe_vault"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/maidsafe_vault/latest"
repository = "https://github.com/maidsafe/maidsafe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
docopt = "*"
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "*"
lru_time_cache = "*"
crust = "*"
routing = "*"
maidsafe_types = "*"

[dev-dependencies]
rand = "*"
