[package]
name = "safe_vault"
version = "0.2.1"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/safe_vault/latest"
repository = "https://github.com/maidsafe/safe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
# ---- Non-MaidSafe -----
cbor = "~0.3.16"
log = "~0.3.3"
env_logger = "~0.3.2"
rand = "~0.3.12"
rustc-serialize = "~0.3.16"
sodiumoxide = "~0.0.9"
tempdir = "~0.3.4"
time = "~0.1.34"

# ---- MaidSafe ------
crust = "~0.5.1"
lru_time_cache = "~0.2.4"
routing = "~0.4.2"

[features]
use-mock-routing = []
