[package]

name = "maidsafe_vault"
version = "0.0.1"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/maidsafe_vault/"
repository = "https://github.com/dirvine/maidsafe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
bchannel = "*"
lru-cache = "*"
time = "*"

[dependencies.maidsafe_types]
git = "https://github.com/dirvine/maidsafe_types"

#[dependencies.utp]
#git = "https://github.com/meqif/rust-utp"

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide"

[dependencies.Routing]
path = "../../maidsafe-routing/routing"
