[package]

name = "maidsafe_vault"
version = "0.0.3"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/maidsafe_vault/"
repository = "https://github.com/dirvine/maidsafe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "*"
rand = "*"
[dependencies.lru_time_cache]
git = "https://github.com/dirvine/lru_time_cache.git"
[dependencies.routing]
git = "https://github.com/dirvine/routing.git"
[dependencies.maidsafe_types]
path = "../maidsafe_types"
