max_width = 100
ideal_width = 100
leeway = 0
tab_spaces = 4
newline_style = "Unix"
fn_brace_style = "PreferSameLine"
fn_return_indent = "WithArgs"
fn_args_paren_newline = true
fn_args_density = "Tall"
fn_args_layout = "Visual"
fn_arg_indent = "Visual"
where_density = "Tall"
where_indent = "Tabbed"
where_layout = "Vertical"
where_pred_indent = "Visual"
generics_indent = "Visual"
struct_trailing_comma = "Vertical"
struct_lit_trailing_comma = "Vertical"
struct_lit_style = "Block"
enum_trailing_comma = true
report_todo = "Always"
report_fixme = "Always"
reorder_imports = true
expr_indent_style = "Tabbed"
closure_indent_style = "Visual"
single_line_if_else = false
format_strings = true
