#
# This will build safe vault using docker-compose v3.3 which requires Docker version 17.06.00+.
# This compose file sets a variety of arguments (args) using environment variables. The values to
# these variables can be specified in the ../../.env file. Simply rename ../../.env.example to .env
# and make your changes (if needed). The .env file is system specific and will not be committed to git 
# unless it is manually forced. (see the ../../.gitignore file).
#
# @see    : ./.env.example
# @link   : https://docs.docker.com/compose/compose-file/
# @link   : https://docs.docker.com/compose/env-file/
# @example: docker-compose -p safevault up --build -d
#
version: '3.3'

services:
    safe_vault:
        env_file: 
          - ../../.env
        build: 
          context : ../../
          args    :
              RUST_LOG                                   : ${RUST_LOG}
              SAFE_VAULT_HARD_CODED_CONTACTS             : ${SAFE_VAULT_HARD_CODED_CONTACTS}
              SAFE_VAULT_WHITELISTED_NODE_IPS            : ${SAFE_VAULT_WHITELISTED_NODE_IPS}
              SAFE_VAULT_WHITELISTED_CLIENT_IPS          : ${SAFE_VAULT_WHITELISTED_CLIENT_IPS}
              SAFE_VAULT_TCP_ACCEPTOR_PORT               : ${SAFE_VAULT_TCP_ACCEPTOR_PORT}
              SAFE_VAULT_FORCE_ACCEPTOR_PORT_IN_EXT_EP   : ${SAFE_VAULT_FORCE_ACCEPTOR_PORT_IN_EXT_EP}
              SAFE_VAULT_SERVICE_DISCOVERY_PORT          : ${SAFE_VAULT_SERVICE_DISCOVERY_PORT}
              SAFE_VAULT_BOOTSTRAP_CACHE_NAME            : ${SAFE_VAULT_BOOTSTRAP_CACHE_NAME}
              SAFE_VAULT_NETWORK_NAME                    : ${SAFE_VAULT_NETWORK_NAME}
              SAFE_VAULT_DISABLE_REACHABILITY_REQUIREMENT: ${SAFE_VAULT_DISABLE_REACHABILITY_REQUIREMENT}
              SAFE_VAULT_ALLOW_MULTIPLE_LAN_NODES        : ${SAFE_VAULT_ALLOW_MULTIPLE_LAN_NODES}
              SAFE_VAULT_DISABLE_CLIENT_RATE_LIMITER     : ${SAFE_VAULT_DISABLE_CLIENT_RATE_LIMITER}
              SAFE_VAULT_DISABLE_RESOURCE_PROOF          : ${SAFE_VAULT_DISABLE_RESOURCE_PROOF}
              SAFE_VAULT_MIN_SECTION_SIZE                : ${SAFE_VAULT_MIN_SECTION_SIZE}
              SAFE_VAULT_WALLET_ADDRESS                  : ${SAFE_VAULT_WALLET_ADDRESS}
              SAFE_VAULT_MAX_CAPACITY                    : ${SAFE_VAULT_MAX_CAPACITY}
              SAFE_VAULT_DISABLE_MUTATION_LIMIT          : ${SAFE_VAULT_DISABLE_MUTATION_LIMIT}
              SAFE_VAULT_LOG_LEVEL_ASYNC_CONSOLE_FILTERS : ${SAFE_VAULT_LOG_LEVEL_ASYNC_CONSOLE_FILTERS}
              SAFE_VAULT_LOG_LEVEL_ROOT                  : ${SAFE_VAULT_LOG_LEVEL_ROOT}
              SAFE_VAULT_LOG_LEVEL_CRUST                 : ${SAFE_VAULT_LOG_LEVEL_CRUST}
              SAFE_VAULT_LOG_LEVEL_ROUTING               : ${SAFE_VAULT_LOG_LEVEL_ROUTING}
              SAFE_VAULT_LOG_LEVEL_ROUTING_STATS         : ${SAFE_VAULT_LOG_LEVEL_ROUTING_STATS}
              SAFE_VAULT_LOG_LEVEL_SAFE_VAULT            : ${SAFE_VAULT_LOG_LEVEL_SAFE_VAULT}
        ports:
            - 5000:5000
            - 5100:5100
